// src/lib/db/mock-data.ts
import type {
  WeeklyKPI,
  TeamMember,
  Experiment,
  WeeklyPlan,
  KPIAlert,
  User,
} from '@/types'

// ─── USERS ────────────────────────────────────────────────────────────────
export const USERS: User[] = [
  {
    id: 'user-001',
    name: 'Abdullah Al-Ghamdi',
    nameAr: 'عبدالله الغامدي',
    email: 'ceo@aman.sa',
    role: 'CEO',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-002',
    name: 'Omar Hassan',
    nameAr: 'عمر حسن',
    email: 'cto@aman.sa',
    role: 'CTO',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-003',
    name: 'Sara Al-Mutairi',
    nameAr: 'سارة المطيري',
    email: 'coo@aman.sa',
    role: 'COO',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-004',
    name: 'Khalid Al-Zahrani',
    nameAr: 'خالد الزهراني',
    email: 'bd1@aman.sa',
    role: 'BD',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-005',
    name: 'Nora Al-Otaibi',
    nameAr: 'نورة العتيبي',
    email: 'bd2@aman.sa',
    role: 'BD',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'user-006',
    name: 'Admin User',
    nameAr: 'المسؤول',
    email: 'admin@aman.sa',
    role: 'ADMIN',
    createdAt: new Date('2024-01-01'),
  },
]

// Hashed passwords for demo (all passwords are "Aman@2024!")
export const USER_CREDENTIALS: Record<string, string> = {
  'ceo@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
  'cto@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
  'coo@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
  'bd1@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
  'bd2@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
  'admin@aman.sa': '$2b$10$YKm0WnBVhXBtOCuKlYjXX.8tLQXNe5XvG8ZKVVrS0rYZjMQ.xf.XS',
}

// ─── WEEKLY KPI DATA (12 weeks) ─────────────────────────────────────────
export const WEEKLY_KPIS: WeeklyKPI[] = [
  {
    weekId: 'W2024-06',
    weekStart: new Date('2024-02-05'),
    weekEnd: new Date('2024-02-11'),
    transactions: 4820,
    gmv: 842000,
    revenue: 46310,
    wau: 10240,
    repeatRate: 20.1,
    takeRate: 5.5,
    completionRate: 71.2,
    disputeRate: 3.2,
    timeToTransaction: 2.8,
    conversionRate: 27.4,
    growthRate: 4.2,
  },
  {
    weekId: 'W2024-07',
    weekStart: new Date('2024-02-12'),
    weekEnd: new Date('2024-02-18'),
    transactions: 5120,
    gmv: 896000,
    revenue: 49280,
    wau: 10820,
    repeatRate: 20.8,
    takeRate: 5.5,
    completionRate: 72.1,
    disputeRate: 3.1,
    timeToTransaction: 2.7,
    conversionRate: 28.1,
    growthRate: 6.2,
  },
  {
    weekId: 'W2024-08',
    weekStart: new Date('2024-02-19'),
    weekEnd: new Date('2024-02-25'),
    transactions: 5420,
    gmv: 948500,
    revenue: 52168,
    wau: 11200,
    repeatRate: 21.4,
    takeRate: 5.5,
    completionRate: 72.8,
    disputeRate: 3.0,
    timeToTransaction: 2.6,
    conversionRate: 28.9,
    growthRate: 5.9,
  },
  {
    weekId: 'W2024-09',
    weekStart: new Date('2024-02-26'),
    weekEnd: new Date('2024-03-03'),
    transactions: 5810,
    gmv: 1016750,
    revenue: 55921,
    wau: 11800,
    repeatRate: 21.9,
    takeRate: 5.5,
    completionRate: 71.4,
    disputeRate: 3.3,
    timeToTransaction: 2.7,
    conversionRate: 29.3,
    growthRate: 7.2,
  },
  {
    weekId: 'W2024-10',
    weekStart: new Date('2024-03-04'),
    weekEnd: new Date('2024-03-10'),
    transactions: 6120,
    gmv: 1071000,
    revenue: 58905,
    wau: 12300,
    repeatRate: 22.4,
    takeRate: 5.5,
    completionRate: 70.8,
    disputeRate: 3.4,
    timeToTransaction: 2.8,
    conversionRate: 29.8,
    growthRate: 5.3,
  },
  {
    weekId: 'W2024-11',
    weekStart: new Date('2024-03-11'),
    weekEnd: new Date('2024-03-17'),
    transactions: 6380,
    gmv: 1116500,
    revenue: 61408,
    wau: 12850,
    repeatRate: 22.8,
    takeRate: 5.5,
    completionRate: 71.2,
    disputeRate: 3.5,
    timeToTransaction: 2.9,
    conversionRate: 30.1,
    growthRate: 4.2,
  },
  {
    weekId: 'W2024-12',
    weekStart: new Date('2024-03-18'),
    weekEnd: new Date('2024-03-24'),
    transactions: 6650,
    gmv: 1163750,
    revenue: 64006,
    wau: 13380,
    repeatRate: 23.1,
    takeRate: 5.5,
    completionRate: 69.8,
    disputeRate: 3.6,
    timeToTransaction: 3.0,
    conversionRate: 30.4,
    growthRate: 4.2,
  },
  {
    weekId: 'W2024-13',
    weekStart: new Date('2024-03-25'),
    weekEnd: new Date('2024-03-31'),
    transactions: 6890,
    gmv: 1205750,
    revenue: 66316,
    wau: 13900,
    repeatRate: 23.4,
    takeRate: 5.5,
    completionRate: 68.9,
    disputeRate: 3.8,
    timeToTransaction: 3.1,
    conversionRate: 30.7,
    growthRate: 3.6,
  },
  {
    weekId: 'W2024-14',
    weekStart: new Date('2024-04-01'),
    weekEnd: new Date('2024-04-07'),
    transactions: 7100,
    gmv: 1242500,
    revenue: 68338,
    wau: 14350,
    repeatRate: 23.6,
    takeRate: 5.5,
    completionRate: 67.9,
    disputeRate: 4.0,
    timeToTransaction: 3.2,
    conversionRate: 30.9,
    growthRate: 3.1,
  },
  {
    weekId: 'W2024-15',
    weekStart: new Date('2024-04-08'),
    weekEnd: new Date('2024-04-14'),
    transactions: 7140,
    gmv: 1249500,
    revenue: 68723,
    wau: 14480,
    repeatRate: 23.5,
    takeRate: 5.5,
    completionRate: 68.2,
    disputeRate: 3.9,
    timeToTransaction: 3.2,
    conversionRate: 30.8,
    growthRate: 0.6,
  },
  {
    weekId: 'W2024-16',
    weekStart: new Date('2024-04-15'),
    weekEnd: new Date('2024-04-21'),
    transactions: 6730,
    gmv: 1177750,
    revenue: 64776,
    wau: 14100,
    repeatRate: 23.7,
    takeRate: 5.5,
    completionRate: 67.4,
    disputeRate: 4.1,
    timeToTransaction: 3.3,
    conversionRate: 31.2,
    growthRate: -5.7,
  },
  {
    weekId: 'W2024-17',
    weekStart: new Date('2024-04-22'),
    weekEnd: new Date('2024-04-28'),
    transactions: 7284,
    gmv: 1274700,
    revenue: 70109,
    wau: 14820,
    repeatRate: 23.8,
    takeRate: 5.5,
    completionRate: 67.4,
    disputeRate: 4.1,
    timeToTransaction: 3.1,
    conversionRate: 31.2,
    growthRate: 8.2,
  },
]

export const CURRENT_WEEK_KPI = WEEKLY_KPIS[WEEKLY_KPIS.length - 1]
export const PREVIOUS_WEEK_KPI = WEEKLY_KPIS[WEEKLY_KPIS.length - 2]

// ─── KPI ALERTS ──────────────────────────────────────────────────────────
export const KPI_ALERTS: KPIAlert[] = [
  {
    id: 'alert-001',
    type: 'CRITICAL',
    metric: 'completionRate',
    message: 'Completion Rate at 67.4% — below 70% threshold. Immediate action required.',
    messageAr: 'نسبة الإتمام عند 67.4% — أقل من الحد الأدنى 70%. مطلوب إجراء فوري.',
    threshold: 70,
    currentValue: 67.4,
    triggeredAt: new Date('2024-04-22T09:00:00'),
    resolved: false,
  },
  {
    id: 'alert-002',
    type: 'WARNING',
    metric: 'repeatRate',
    message: 'Repeat Rate at 23.8% — below 25% target. Monitor closely.',
    messageAr: 'معدل التكرار عند 23.8% — أقل من هدف 25%. يتطلب المراقبة.',
    threshold: 25,
    currentValue: 23.8,
    triggeredAt: new Date('2024-04-22T09:00:00'),
    resolved: false,
  },
  {
    id: 'alert-003',
    type: 'WARNING',
    metric: 'disputeRate',
    message: 'Dispute Rate increased to 4.1% — up 0.8% from 2 weeks ago.',
    messageAr: 'ارتفع معدل النزاعات إلى 4.1% — بزيادة 0.8% عن أسبوعين مضت.',
    threshold: 4.0,
    currentValue: 4.1,
    triggeredAt: new Date('2024-04-24T14:00:00'),
    resolved: false,
  },
]

// ─── TEAM PERFORMANCE ─────────────────────────────────────────────────────
export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-001',
    userId: 'user-001',
    name: 'Abdullah Al-Ghamdi',
    nameAr: 'عبدالله الغامدي',
    role: 'CEO',
    weeklyTargets: [
      { metric: 'Weekly Review', target: 1, actual: 1, unit: 'session', progress: 100 },
      { metric: 'Decisions Made', target: 3, actual: 2, unit: 'decisions', progress: 67 },
      { metric: 'Stakeholder Updates', target: 2, actual: 1, unit: 'updates', progress: 50 },
    ],
    currentPerformance: 72,
    status: 'YELLOW',
  },
  {
    id: 'tm-002',
    userId: 'user-002',
    name: 'Omar Hassan',
    nameAr: 'عمر حسن',
    role: 'CTO',
    weeklyTargets: [
      { metric: 'Completion Fix', target: 1, actual: 0, unit: 'deploy', progress: 45 },
      { metric: 'Tech Debt Items', target: 3, actual: 2, unit: 'items', progress: 67 },
      { metric: 'Gateway SLA Review', target: 1, actual: 1, unit: 'review', progress: 100 },
    ],
    currentPerformance: 54,
    status: 'RED',
  },
  {
    id: 'tm-003',
    userId: 'user-003',
    name: 'Sara Al-Mutairi',
    nameAr: 'سارة المطيري',
    role: 'COO',
    weeklyTargets: [
      { metric: 'Process Docs', target: 5, actual: 5, unit: 'docs', progress: 100 },
      { metric: 'Team Syncs', target: 3, actual: 3, unit: 'meetings', progress: 100 },
      { metric: 'SLA Reviews', target: 2, actual: 2, unit: 'reviews', progress: 100 },
    ],
    currentPerformance: 100,
    status: 'GREEN',
  },
  {
    id: 'tm-004',
    userId: 'user-004',
    name: 'Khalid Al-Zahrani',
    nameAr: 'خالد الزهراني',
    role: 'BD',
    weeklyTargets: [
      { metric: 'Enterprise Demos', target: 5, actual: 3, unit: 'demos', progress: 60 },
      { metric: 'Proposals Sent', target: 4, actual: 4, unit: 'proposals', progress: 100 },
      { metric: 'Pipeline Value', target: 500000, actual: 420000, unit: 'SAR', progress: 84 },
    ],
    currentPerformance: 81,
    status: 'GREEN',
  },
  {
    id: 'tm-005',
    userId: 'user-005',
    name: 'Nora Al-Otaibi',
    nameAr: 'نورة العتيبي',
    role: 'BD',
    weeklyTargets: [
      { metric: 'Enterprise Demos', target: 3, actual: 1, unit: 'demos', progress: 33 },
      { metric: 'Proposals Sent', target: 3, actual: 1, unit: 'proposals', progress: 33 },
      { metric: 'Pipeline Value', target: 300000, actual: 80000, unit: 'SAR', progress: 27 },
    ],
    currentPerformance: 31,
    status: 'RED',
  },
]

// ─── EXPERIMENTS ─────────────────────────────────────────────────────────
export const EXPERIMENTS: Experiment[] = [
  {
    id: 'exp-001',
    hypothesis: 'Adding SMS reminder for pending transactions will increase completion rate by 5%',
    hypothesisAr: 'إضافة تذكير SMS للعمليات المعلقة سيرفع نسبة الإتمام بنسبة 5%',
    kpiTarget: 'Completion Rate +5%',
    kpiImpactExpected: 5.0,
    kpiImpactActual: 3.2,
    status: 'COMPLETE',
    verdict: 'KEEP',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2024-04-15'),
    ownerId: 'user-002',
  },
  {
    id: 'exp-002',
    hypothesis: 'Extended payment window from 24h to 48h increases completion rate by 8%',
    hypothesisAr: 'تمديد نافذة الدفع من 24 ساعة إلى 48 ساعة سيرفع نسبة الإتمام بنسبة 8%',
    kpiTarget: 'Completion Rate +8%',
    kpiImpactExpected: 8.0,
    kpiImpactActual: 1.1,
    status: 'COMPLETE',
    verdict: 'REVIEW',
    startDate: new Date('2024-03-18'),
    endDate: new Date('2024-04-07'),
    ownerId: 'user-003',
  },
  {
    id: 'exp-003',
    hypothesis: 'Trust badge on seller landing page increases conversion by 10%',
    hypothesisAr: 'شارة الثقة في صفحة البائع ترفع معدل التحويل بنسبة 10%',
    kpiTarget: 'Conversion Rate +10%',
    kpiImpactExpected: 10.0,
    kpiImpactActual: 8.4,
    status: 'COMPLETE',
    verdict: 'KEEP',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-03-21'),
    ownerId: 'user-004',
  },
  {
    id: 'exp-004',
    hypothesis: 'Reduced fee for transactions under 10K SAR will increase new user acquisition by 15%',
    hypothesisAr: 'تخفيض الرسوم على العمليات أقل من 10,000 ريال سيزيد اكتساب المستخدمين الجدد بنسبة 15%',
    kpiTarget: 'New Users +15%',
    kpiImpactExpected: 15.0,
    kpiImpactActual: -2.1,
    status: 'COMPLETE',
    verdict: 'KILL',
    startDate: new Date('2024-02-12'),
    endDate: new Date('2024-03-04'),
    ownerId: 'user-001',
  },
  {
    id: 'exp-005',
    hypothesis: 'In-app dispute resolution chat reduces dispute resolution time from 4.2 to 2 days',
    hypothesisAr: 'محادثة حل النزاعات داخل التطبيق تقلل وقت الحل من 4.2 أيام إلى يومين',
    kpiTarget: 'Dispute Resolution Time -50%',
    kpiImpactExpected: -50.0,
    status: 'RUNNING',
    startDate: new Date('2024-04-20'),
    ownerId: 'user-003',
  },
]

// ─── WEEKLY PLAN ──────────────────────────────────────────────────────────
export const CURRENT_WEEKLY_PLAN: WeeklyPlan = {
  id: 'wplan-017',
  weekStart: new Date('2024-04-22'),
  kpiReview: [
    { metric: 'Transactions', target: 7000, actual: 7284, status: 'GREEN', note: 'Up 8.3% WoW — strong momentum', noteAr: 'ارتفع 8.3% أسبوعياً — زخم قوي' },
    { metric: 'GMV', target: 1200000, actual: 1274700, status: 'GREEN', note: 'Up 11.2% WoW', noteAr: 'ارتفع 11.2% أسبوعياً' },
    { metric: 'Completion Rate', target: 70, actual: 67.4, status: 'RED', note: 'CRITICAL: Below 70% threshold', noteAr: 'حرج: أقل من الحد الأدنى 70%' },
    { metric: 'Repeat Rate', target: 25, actual: 23.8, status: 'YELLOW', note: 'Below target, declining slowly', noteAr: 'أقل من الهدف، يتراجع ببطء' },
    { metric: 'Dispute Rate', target: 3.5, actual: 4.1, status: 'RED', note: 'Rising — monitor daily', noteAr: 'يرتفع — مراقبة يومية مطلوبة' },
  ],
  problems: [
    { id: 'prob-001', priority: 'P1', description: 'Payment gateway timeouts 2PM-5PM Gulf time causing completion failures', descriptionAr: 'انتهاء مهلة بوابة الدفع بين 2-5 مساءً بتوقيت الخليج يسبب فشل الإتمام', owner: 'CTO', status: 'IN_PROGRESS' },
    { id: 'prob-002', priority: 'P2', description: 'BD2 pipeline empty — no new demos this week, intervention needed', descriptionAr: 'خط أنابيب المبيعات 2 فارغ — لا عروض جديدة هذا الأسبوع، تدخل مطلوب', owner: 'COO', status: 'OPEN' },
    { id: 'prob-003', priority: 'P3', description: 'Dispute resolution SLA at 4.2 days — target is 2 days', descriptionAr: 'معدل اتفاقية مستوى الخدمة لحل النزاعات 4.2 أيام — الهدف يومان', owner: 'COO', status: 'OPEN' },
  ],
  focusOfWeek: 'Fix Completion Rate to 72%+. Every team decision this week must serve this goal.',
  focusOfWeekAr: 'رفع نسبة الإتمام إلى 72%+. كل قرار هذا الأسبوع يجب أن يخدم هذا الهدف.',
  killList: ['New feature development', 'Marketing campaigns', 'Non-critical BD outreach', 'Partnership announcements'],
  killListAr: ['تطوير ميزات جديدة', 'حملات التسويق', 'توسع المبيعات غير الضروري', 'إعلانات الشراكات'],
  decisions: [
    { id: 'dec-001', description: 'Paused all new feature development until completion rate fixed', descriptionAr: 'تجميد تطوير المميزات الجديدة حتى إصلاح معدل الإتمام', decidedBy: 'CEO', decidedAt: new Date('2024-04-23'), status: 'DONE' },
    { id: 'dec-002', description: 'Emergency gateway SLA review scheduled with payment provider', descriptionAr: 'جدولة مراجعة طارئة لاتفاقية بوابة الدفع مع المزود', decidedBy: 'CTO', decidedAt: new Date('2024-04-24'), status: 'DONE' },
    { id: 'dec-003', description: 'BD2 performance review — 30-day improvement plan or restructure', descriptionAr: 'مراجعة أداء المبيعات 2 — خطة تحسين 30 يوماً أو إعادة هيكلة', decidedBy: 'CEO', decidedAt: new Date('2024-04-27'), status: 'PENDING' },
  ],
  generatedAt: new Date('2024-04-22T08:00:00'),
}

// ─── GA MOCK DATA ─────────────────────────────────────────────────────────
export const GA_WEEKLY_DATA = [
  { date: '2024-04-21', sessions: 6200, users: 4800, pageviews: 18600, bounceRate: 38.2, avgSessionDuration: 252, conversionRate: 30.8, transactions: 1842 },
  { date: '2024-04-22', sessions: 7100, users: 5500, pageviews: 21300, bounceRate: 37.8, avgSessionDuration: 258, conversionRate: 31.0, transactions: 2201 },
  { date: '2024-04-23', sessions: 6800, users: 5200, pageviews: 20400, bounceRate: 38.5, avgSessionDuration: 248, conversionRate: 30.6, transactions: 2081 },
  { date: '2024-04-24', sessions: 7400, users: 5700, pageviews: 22200, bounceRate: 37.1, avgSessionDuration: 264, conversionRate: 31.5, transactions: 2331 },
  { date: '2024-04-25', sessions: 8100, users: 6200, pageviews: 24300, bounceRate: 36.9, avgSessionDuration: 271, conversionRate: 32.1, transactions: 2600 },
  { date: '2024-04-26', sessions: 5200, users: 4000, pageviews: 15600, bounceRate: 40.2, avgSessionDuration: 238, conversionRate: 28.8, transactions: 1498 },
  { date: '2024-04-27', sessions: 4900, users: 3800, pageviews: 14700, bounceRate: 41.0, avgSessionDuration: 231, conversionRate: 28.2, transactions: 1382 },
]

export function getKPIDelta(current: number, previous: number) {
  const delta = current - previous
  const percentage = previous !== 0 ? (delta / previous) * 100 : 0
  return {
    value: delta,
    percentage,
    direction: delta > 0 ? ('up' as const) : delta < 0 ? ('down' as const) : ('stable' as const),
  }
}

export function getLastNWeeks(n: number): WeeklyKPI[] {
  return WEEKLY_KPIS.slice(-n)
}
